const universities = 
[
    { label: "University of Petroleum and Energy Studies"    },
    { label: "DAV Institute of Engineering & Technology"    },
    { label: "Lovely Professional University"    },
    { label: "Somaiya Vidyavihar"    },
    { label: "NorthCap University"    },
    { label: "Dharamsinh Desai University"    },
    { label: "University of Health Sciences Andhra Pradesh"    },
    { label: "Allahabad Agricultural Institute, Deemed University"    },
    { label: "Assam Agricultural University"    },
    { label: "Ahmedabad University"    },
    { label: "All India Institute of Medical Sciences"    },
    { label: "AISECT University"    },
    { label: "Alagappa University"    },
    { label: "Allahabad University"    },
    { label: "Open International University for Alternative Medicines"    },
    { label: "Indian Board of Alternative Medicine"    },
    { label: "Amity University"    },
    { label: "Amrita Vishwa Vidyapeetham (Deemed University)"    },
    { label: "Amravati University"    },
    { label: "Aligarh Muslim University"    },
    { label: "Andhra University"    },
    { label: "Acharya Ranga Agricultural University"    },
    { label: "Annamalai University"    },
    { label: "Anna University of Technology, Tirunelveli"    },
    { label: "Anna University"    },
    { label: "Awadhesh Pratap Singh University"    },
    { label: "ARYA Institute of Engineering & Technology"    },
    { label: "Assam University"    },
    { label: "Gujarat Ayurved University"    },
    { label: "Dr. Babasaheb Ambedkar Marathwada Universtiy"    },
    { label: "Berhampur University"    },
    { label: "Banasthali University"    },
    { label: "Bankura University"    },
    { label: "Birsa Agricultural University"    },
    { label: "Babasaheb Bhimrao Ambedkar University"    },
    { label: "Bidhan Chandra Agricultural University"    },
    { label: "Bharathidasan University"    },
    { label: "Bengal Engineering College"    },
    { label: "Bangalore University"    },
    { label: "Bhagwant University"    },
    { label: "Bharathiar University"    },
    { label: "Bharath Institue Of Higher Education & Research"    },
    { label: "Bharati Vidyapeeth University"    },
    { label: "Bhavnagar University"    },
    { label: "Banaras Hindu University"    },
    { label: "Orissa University of Agriculture and Technology"    },
    { label: "Birla Institute of Technology, Ranchi"    },
    { label: "Birla Institute of Technology and Science"    },
    { label: "Bhupendra Narayan Mandal University"    },
    { label: "Biju Pattnaik University of Technology"    },
    { label: "B. R. Ambedkar Bihar University"    },
    { label: "Dr. B.R. Ambedkar Open University"    },
    { label: "Dr. B. R. Ambedkar National Institute of Technology Jalandhar"    },
    { label: "Dr. Bhim Rao Abdekar University"    },
    { label: "B. S. Abdur Rahman University"    },
    { label: "Barkatullah University"    },
    { label: "Bundelkhand University"    },
    { label: "University of Burdwan"    },
    { label: "University of Calcutta"    },
    { label: "Central Agricultural University"    },
    { label: "Chaudhary Charan Singh University"    },
    { label: "Ch. Charan Singh University"    },
    { label: "Center for Entrepreneurship and Small Business Management"    },
    { label: "Christ University"    },
    { label: "Central Institute of English and Foreign Languages"    },
    { label: "Central Institute of Fisheries Education"    },
    { label: "Central Institute of Higher Tibetan Studies"    },
    { label: "CMJ University"    },
    { label: "Chandra Shekhar Azad University of Agriculture and Technology"    },
    { label: "Cochin University of Science and Technology"    },
    { label: "Dr. C.V. Raman University"    },
    { label: "Dhirubhai Ambani Institute of Information and Communication Technology"    },
    { label: "Darul Huda Islamic University"    },
    { label: "Dav University"    },
    { label: "Devi Ahilya University of Indore"    },
    { label: "Dr. Babasaheb Ambedkar Technological University"    },
    { label: "Konkan Agricultural University"    },
    { label: "Tamil Nadu Agricultural University"    },
    { label: "Delhi College of Engineering (DCE)"    },
    { label: "Deen Dayal Upadhyay Gorakhpur University"    },
    { label: "Deccan College Postgraduate and Research Institute"    },
    { label: "Dayalbagh Educational Institute"    },
    { label: "Dibrugarh University"    },
    { label: "Dravidian University"    },
    { label: "University of Delhi"    },
    { label: "Dr. D.Y. Patil University"    },
    { label: "Eiilm University"    },
    { label: "Fatima mata national college kollam kerala"    },
    { label: "Forest Research Institute Dehradun"    },
    { label: "Govind Ballabh Pant University of Agriculture and Technology"    },
    { label: "Guru Ghasidas University"    },
    { label: "Gokhale Institute of Politics and Economics"    },
    { label: "Gandhi Institute of Technology and Managment"    },
    { label: "Guru Jambeshwar University"    },
    { label: "Gurukula Kangri University"    },
    { label: "Guru Nanak Dev University"    },
    { label: "Global Open University , Nagaland"    },
    { label: "Gujarat Technological University Ahmedabad"    },
    { label: "Gujarat University Ahmedabad"    },
    { label: "Gulbarga University"    },
    { label: "Gauhati University"    },
    { label: "Gurukul University"    },
    { label: "CCS Haryana Agricultural University"    },
    { label: "Chaudhary Charan Singh Haryana Agricultural University"    },
    { label: "Himachal Pradesh Agricultural University"    },
    { label: "Hemwati Nandan Bahuguna Garhwal University"    },
    { label: "Hidayatullah National Law University, Raipur"    },
    { label: "Sri Ramachardra Medical College and Research Institute"    },
    { label: "Himachal Pradesh University"    },
    { label: "Indian Agricultural Research Institute"    },
    { label: "IASE (Institute of Advanced Studies) Deemed University"    },
    { label: "ICFAI University"    },
    { label: "ICFAI University, Dehradun"    },
    { label: "ICFAI University, Tripura"    },
    { label: "ICFAI University, Sikkim"    },
    { label: "ICFAI University, Mizoram"    },
    { label: "ICFAI University, Meghalaya"    },
    { label: "ICFAI University, Jharkhand"    },
    { label: "ICFAI University, Nagaland"    },
    { label: "ICFAI University, Jaipur"    },
    { label: "ICFAI University, Raipur"    },
    { label: "ICFAI University, Himachal Pradesh"    },
    { label: "ICFAI University, Hyderabad"    },
    { label: "Indira Gandhi Agricultural University"    },
    { label: "Indira Gandhi Institute of Development and Research"    },
    { label: "Indira Gandhi Institute of Medical Sciences"    },
    { label: "Indira Gandhi National Open University"    },
    { label: "Indian Institute of Information Technology"    },
    { label: "Indian Institute of Information Technology and Management - Kerala"    },
    { label: "Indian Institute of Information Technology and Management - Gwalior"    },
    { label: "Indraprastha Institute of Information Technology, Delhi"    },
    { label: "International Institute of Information Technology, Pune"    },
    { label: "International Institute of Information Technology, Bhubaneswar"    },
    { label: "International Institute of Information Technology, Bangalore"    },
    { label: "Indian Institute of Management, Tiruchirappalli"    },
    { label: "Indian Institute of Information Technology, Guwahati"    },
    { label: "Indian Institute of Information Technology, Vadodara"    },
    { label: "Indian Institute of Information Technology, Kota"    },
    { label: "International Institute for Population Sciences"    },
    { label: "Indian Institute of Science"    },
    { label: "Indian Institute of Technology, Bombay"    },
    { label: "Indian Institute of Technology, Delhi"    },
    { label: "Indian Institute of Technology, Gandhinagar"    },
    { label: "Indian Institute of Technology, Guwahati"},
    { label: "Indian Institute of Technology, Hyderabad"    },
    { label: "Indian Institute of Technology, Kanpur"    },
    { label: "Indian Institute of Technology, Kharagpur"    },
    { label: "Indian Institute of Technology, Madras"    },
    { label: "Madras Institute of Technology"    },
    { label: "Indian Institute of Technology, Roorkee"    },
    { label: "Indian Institute of Technology, Patna"    },
    { label: "Indian Institute of Technology, Indore"    },
    { label: "Indian Institute of Technology, Jodhpur"    },
    { label: "University of Music and Fine Arts"    },
    { label: "Indian Law Institue"    },
    { label: "Indus University"    },
    { label: "Integral University"    },
    { label: "Guru Gobind Singh Indraprastha University"    },
    { label: "Indian School of Business Management and Administration"    },
    { label: "Indian Statistical Institute"    },
    { label: "Indian School of Mines (ISM)"    },
    { label: "Institute of Technology and Management"    },
    { label: "Indian University"    },
    { label: "Indian Veterinary Research Institute"    },
    { label: "Jadavpur University"    },
    { label: "First Global University to teaching Jainism"    },
    { label: "Jamia Hamdard University"    },
    { label: "University of Jammu"    },
    { label: "Jaypee Institute of Information Technology"    },
    { label: "Jiwaji University"    },
    { label: "Jamia Millia Islamia University"    },
    { label: "Jawaharlal Nehru Centre for Advanced  Scientific Research"    },
    { label: "Jawaharlal Nehru Agricultural University"    },
    { label: "Jawaharlal Nehru Technological University"    },
    { label: "Jawaharlal Nehru University"    },
    { label: "Jaipur National University"    },
    { label: "Jodhpur National University"    },
    { label: "Jai Prakash University"    },
    { label: "Rajasthan Vidyapeeth University"    },
    { label: "Jain Vishva Bharati Institute"    },
    { label: "Kalinga University"    },
    { label: "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya"    },
    { label: "Kannada University"    },
    { label: "Kannur University"    },
    { label: "Chhatrapati Shahu Ji Maharaj University"    },
    { label: "Kanpur University"    },
    { label: "Karnataka State Open University"    },
    { label: "Karpagam University"    },
    { label: "Karunya Institute Of Technology ( Deemed University)"    },
    { label: "University of Kashmir"    },
    { label: "Kerala Agricultural University"    },
    { label: "University of Kerala"    },
    { label: "Kohinoor School of Hospitality Management"    },
    { label: "University of Kalyani"    },
    { label: "Krishna University"    },
    { label: "Kameshwar Singh Darbhanga Sanskrit University"    },
    { label: "Karnataka State Law University"    },
    { label: "Karnatak University"    },
    { label: "Kerala University of Fisheries and Ocean Sciences"    },
    { label: "Kurukshetra University"    },
    { label: "Kumaraguru College of Technology"    },
    { label: "Kumaun University"    },
    { label: "Kuvempu University"    },
    { label: "Kakatiya University"    },
    { label: "L.D.College of Engineering"    },
    { label: "Lakshmibai National Institute of Physical Education"    },
    { label: "Lalit Narayan Mithila University"    },
    { label: "University of Lucknow"    },
    { label: "Mar Athanasios College for Advanced Studies"    },
    { label: "Magadh University"    },
    { label: "Mangalore University"    },
    { label: "Manipal University"    },
    { label: "Manipur University"    },
    { label: "Moulana Azad national Urdu University"    },
    { label: "Makanlal Chutur Vedi University"    },
    { label: "Makhanlal Chaturvedi National University of Journalism and Communication"    },
    { label: "Maharshi Dayanand Sarswati University Ajmer"    },
    { label: "Maharishi Dayanand University, Rohtak (Haryana )"    },
    { label: "Mahatma Gandhi Kashi Vidyapith"    },
    { label: "Maharaja Ganga Singh University, Bikaner"    },
    { label: "Mahatma Gandhi University, Kerala"    },
    { label: "Mahatma Jyotiba Phule Rohilkhand University Bareilly"    },
    { label: "Madurai Kamaraj University"    },
    { label: "Marathwada Agricultural University"    },
    { label: "Mohan Lal Sukhadia University"    },
    { label: "Motilal Nehru National Institute Of Technology"    },
    { label: "Madhya Pradesh Bhoj (Open) University"    },
    { label: "Mahatma Phule Agricultural University"    },
    { label: "Maharaja Sayajirao University of Baroda"    },
    { label: "University of Mumbai"    },
    { label: "Acharya Nagarjuna University"    },
    { label: "Nagaland University"    },
    { label: "Nagpur University"    },
    { label: "Nalanda Open University"    },
    { label: "National Museum Institute of History of Art, Conservation and Museology"    },
    { label: "University of North Bengal"    },
    { label: "National Dairy Research Institute"    },
    { label: "Narendra Deva University of Agriculture and Technology"    },
    { label: "North Eastern Hill University"    },
    { label: "Hemchandracharay North Gujarat University"    },
    { label: "National Institute of Mental Health and Neuro Sciences"    },
    { label: "Nizam's Institute of Medical Sciences"    },
    { label: "Institute of Management Studies"    },
    { label: "Nirma University"    },
    { label: "National Institute of Industrial Engineering"    },
    { label: "National Institute of Technology Agartala"    },
    { label: "National Institute of Technology Andhra Pradesh"    },
    { label: "National Institute of Technology Arunachal Pradesh"    },
    { label: "National Institute of Technology Calicut"    },
    { label: "National Institute of Technology Delhi"    },
    { label: "National Institute of Technology Durgapur"    },
    { label: "National Institute of Technology Goa"    },
    { label: "National Institute of Technology Hamirpur"    },
    { label: "National Institute of Technology Jamshedpur"    },
    { label: "National Institute of Technology Kurukshetra"    },
    { label: "National Institute of Technology Manipur"    },
    { label: "National Institute of Technology Meghalaya"    },
    { label: "National Institute of Technology Mizoram"    },
    { label: "National Institute of Technology Nagaland"    },
    { label: "National Institute of Technology Patna"    },
    { label: "National Institute of Technology Puducherry"    },
    { label: "National Institute of Technology Raipur"    },
    { label: "National Institute of Technology Rourkela"    },
    { label: "National Institute of Technology Sikkim"    },
    { label: "National Institute of Technology Silchar"    },
    { label: "National Institute of Technology Srinagar"    },
    { label: "National Institute of Technology Surathkal"    },
    { label: "National Institute of Technology Trichy"    },
    { label: "National Institute of Technology Uttarakhand"    },
    { label: "National Institute of Technology Warangal"    },
    { label: "National Law School of India University"    },
    { label: "Narsee Monjee Institute of Management Studies"    },
    { label: "North Maharashtra University"    },
    { label: "Netaji Subhas Institute of Technology"    },
    { label: "Osmania University"    },
    { label: "Sri Padmavati Women's University"    },
    { label: "Pandit Deendayal Petroleum University"    },
    { label: "Punjab Agricultural University"    },
    { label: "Dr. Panjabrao Deshmukh Krishi Vidyapeeth"    },
    { label: "Parul University"    },
    { label: "Punjab Engineering College"    },
    { label: "Pes University"    },
    { label: "Postgraduate lnstitute of Medical Education and Research"    },
    { label: "Pondicherry University"    },
    { label: "PSG College of Technology"    },
    { label: "Jai Narain Vyas University"    },
    { label: "Punjab Technical University"    },
    { label: "Panjab University"    },
    { label: "Punjabi University Patiala"    },
    { label: "Patna University"    },
    { label: "Rajendra Agricultural University"    },
    { label: "Rabindra Bharati University"    },
    { label: "Ranchi University"    },
    { label: "Rajasthan Agricultural University, Bikaner"    },
    { label: "Rani Durgavati University"    },
    { label: "Rajiv Gandhi Technical University (University of Technology of Madhya Pradesh)"    },
    { label: "Rajiv Gandhi University"    },
    { label: "Rajitlal Institute of Technology & Health Sciences (RITHS)"    },
    { label: "Dr. Ram Manohar Lohia Avadh University"    },
    { label: "Pandit Ravi Shankar Shukla University"    },
    { label: "Rajasthan Technical University"    },
    { label: "Mahatma Gandhi Chitrakut Gramoday University"    },
    { label: "Dr. Hari Singh Gour University, formerly University of Sagar"    },
    { label: "Sambalpur University"    },
    { label: "National Sanskrit University"    },
    { label: "SASTRA Deemed University"    },
    { label: "Sathyabama University"    },
    { label: "Saurashtra University"    },
    { label: "Shanmugha Arts Science Technology and Research Academy"    },
    { label: "Sree Chitra Tirunal Institute for Medical Sciences and Technology"    },
    { label: "Sardarkrushinagar Dantiwada Agricultural University"    },
    { label: "Sanjay Gandhi Postgraduate lnstitute of Medical Sciences"    },
    { label: "South Gujarat University"    },
    { label: "Shobhit University, Meerut"    },
    { label: "Shridhar University"    },
    { label: "Vikrama Simhapuri University"    },
    { label: "Symbiosis International University"    },
    { label: "Shri Jagannath Sanskrit University"    },
    { label: "Sido Kanhu Murmu University"    },
    { label: "Sher-E-Kashmir University of Agricultural Sciences and Technology"    },
    { label: "Sri Krishnadevaraya University"    },
    { label: "Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha"    },
    { label: "SMK Fomra Institute of Technology"    },
    { label: "Sikkim Manipal University of Health, Medical and Technological Sciences"    },
    { label: "Shreemati Nathibai Damodar Thackersey Women's University"    },
    { label: "Sikha 'O' Anushandhan University"    },
    { label: "South Asian University"    },
    { label: "School of Planning and Architecture"    },
    { label: "Periyar University"    },
    { label: "Sardar Patel University"    },
    { label: "Sri Sathya Sai Institute of Higher Learning"    },
    { label: "Sree Rama Krishna Degree College"    },
    { label: "SRM Institute Of Science & Technology ( Deemed University)"    },
    { label: "Swami Ramanand Teerth Marathwada University"    },
    { label: "Sri Sant Gajanan Maharaj College of Engineering"    },
    { label: "Sree Sankaracharya University of Sanskrit"    },
    { label: "Sampurnanand Sanskrit University"    },
    { label: "Solapur University"    },
    { label: "Sardar Vallabhai Patel University of Agriculture Amd Technology"    },
    { label: "Sardar Vallabhbhai National Institute of Technology"    },
    { label: "Sri Venkateswara Institute of Medical Sciences"    },
    { label: "Sri Venkateswara University"    },
    { label: "Tamil University"    },
    { label: "Tamil Nadu Veterinary and Animal Sciences University"    },
    { label: "Thiagarajar College of Engineering"    },
    { label: "Potti Sreeramulu Telugu University"    },
    { label: "Telugu University"    },
    { label: "Tezpur University"    },
    { label: "The New College"    },
    { label: "Thapar Institute of Engineering and Technology"    },
    { label: "Tata Institute of Social Sciences"    },
    { label: "Tilka Manjhi Bhagalpur University"    },
    { label: "Tilak Maharashtra Vidyapeeth"    },
    { label: "Tamil Nadu Dr. Ambedkar Law University"    },
    { label: "Tamil Nadu Dr. M.G.R. Medical University"    },
    { label: "Avinashilingam Institute for Home Science and Higher Education for Women"    },
    { label: "Gandhigram Rural Institute"    },
    { label: "Manonmaniam Sundaranar University"    },
    { label: "Mother Teresa Women's University"    },
    { label: "Maulana Azad National Institute of Technology Bhopal"    },
    { label: "Malaviya National Institute of Technology Jaipur"    },
    { label: "Tripura University"    },
    { label: "Takhatmal Shrivallabh Homoeopathic Medical College"    },
    { label: "Tumkur University"    },
    { label: "Thiruvalluvar University"    },
    { label: "University of Agricultural Sciences, Bangalore"    },
    { label: "University of Agricultural Sciences, Dharwad"    },
    { label: "Uttarakhand Technical University"    },
    { label: "University of Media Arts"    },
    { label: "University of Calicut"    },
    { label: "Goa University"    },
    { label: "University of Mysore"    },
    { label: "University of Pune"    },
    { label: "University of Rajasthan"    },
    { label: "Shivaji University"    },
    { label: "University of Madras"    },
    { label: "University of Hyderabad"    },
    { label: "University of Kota"    },
    { label: "University of Roorkee"    },
    { label: "Uttarakhand Open University"    },
    { label: "Uttar Pradesh Technical University"    },
    { label: "Utkal University"    },
    { label: "VBS Purvanchal University"    },
    { label: "Vinoba Bhave University"    },
    { label: "Vidyasagar University"    },
    { label: "Vignan University"    },
    { label: "Vikram University"    },
    { label: "Vinayaka Mission's Research Foundation-Deemed University"    },
    { label: "Visva-Bharati University"    },
    { label: "Vellore Institute of Technology"    },
    { label: "Veer Kunwar Singh University"    },
    { label: "Vardhaman Mahaveer Open University"    },
    { label: "Visvesvaraya National Institute of Technology"    },
    { label: "Veer Surendra Sai University of Technology"    },
    { label: "Visvesvaraya Technological University"    },
    { label: "West Bengal University of Animal and Fishery Sciences"    },
    { label: "West Bengal University of Technology"    },
    { label: "Yashawantrao Chavan Maharashtra Open University"    },
    { label: "Dr. YS Parmar University of Horticulture and Forestry"    },
    { label: "Charotar University of Science and Technology"    },
    { label: "Navrachana University"    },
    { label: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Gwalior"    },
    { label: "University of Petroleum and Energy Studies"    },
    { label: "DAV Institute of Engineering & Technology"    },
    { label: "Lovely Professional University"    },
    { label: "Somaiya Vidyavihar"    },
    { label: "NorthCap University"    },
    { label: "Dharamsinh Desai University"    },
    { label: "University of Health Sciences Andhra Pradesh"    },
    { label: "Allahabad Agricultural Institute, Deemed University"    },
    { label: "Assam Agricultural University"    },
    { label: "Ahmedabad University"    },
    { label: "All India Institute of Medical Sciences"    },
    { label: "AISECT University"    },
    { label: "Alagappa University"    },
    { label: "Allahabad University"    },
    { label: "Open International University for Alternative Medicines"    },
    { label: "Indian Board of Alternative Medicine"    },
    { label: "Amity University"    },
    { label: "Amrita Vishwa Vidyapeetham (Deemed University)"    },
    { label: "Amravati University"    },
    { label: "Aligarh Muslim University"    },
    { label: "Andhra University"    },
    { label: "Acharya Ranga Agricultural University"    },
    { label: "Annamalai University"    },
    { label: "Anna University of Technology, Tirunelveli"    },
    { label: "Anna University"    },
    { label: "Awadhesh Pratap Singh University"    },
    { label: "ARYA Institute of Engineering & Technology"    },
    { label: "Assam University"    },
    { label: "Gujarat Ayurved University"    },
    { label: "Dr. Babasaheb Ambedkar Marathwada Universtiy"    },
    { label: "Berhampur University"    },
    { label: "Banasthali University"    },
    { label: "Bankura University"    },
    { label: "Birsa Agricultural University"    },
    { label: "Babasaheb Bhimrao Ambedkar University"    },
    { label: "Bidhan Chandra Agricultural University"    },
    { label: "Bharathidasan University"    },
    { label: "Bengal Engineering College"    },
    { label: "Bangalore University"    },
    { label: "Bhagwant University"    },
    { label: "Bharathiar University"    },
    { label: "Bharath Institue Of Higher Education & Research"    },
    { label: "Bharati Vidyapeeth University"    },
    { label: "Bhavnagar University"    },
    { label: "Banaras Hindu University"    },
    { label: "Orissa University of Agriculture and Technology"    },
    { label: "Birla Institute of Technology, Ranchi"    },
    { label: "Birla Institute of Technology and Science"    },
    { label: "Bhupendra Narayan Mandal University"    },
    { label: "Biju Pattnaik University of Technology"    },
    { label: "B. R. Ambedkar Bihar University"    },
    { label: "Dr. B.R. Ambedkar Open University"    },
    { label: "Dr. B. R. Ambedkar National Institute of Technology Jalandhar"    },
    { label: "Dr. Bhim Rao Abdekar University"    },
    { label: "B. S. Abdur Rahman University"    },
    { label: "Barkatullah University"    },
    { label: "Bundelkhand University"    },
    { label: "University of Burdwan"    },
    { label: "University of Calcutta"    },
    { label: "Central Agricultural University"    },
    { label: "Chaudhary Charan Singh University"    },
    { label: "Ch. Charan Singh University"    },
    { label: "Center for Entrepreneurship and Small Business Management"    },
    { label: "Christ University"    },
    { label: "Central Institute of English and Foreign Languages"    },
    { label: "Central Institute of Fisheries Education"    },
    { label: "Central Institute of Higher Tibetan Studies"    },
    { label: "CMJ University"    },
    { label: "Chandra Shekhar Azad University of Agriculture and Technology"    },
    { label: "Cochin University of Science and Technology"    },
    { label: "Dr. C.V. Raman University"    },
    { label: "Dhirubhai Ambani Institute of Information and Communication Technology"    },
    { label: "Darul Huda Islamic University"    },
    { label: "Dav University"    },
    { label: "Devi Ahilya University of Indore"    },
    { label: "Dr. Babasaheb Ambedkar Technological University"    },
    { label: "Konkan Agricultural University"    },
    { label: "Tamil Nadu Agricultural University"    },
    { label: "Delhi College of Engineering (DCE)"    },
    { label: "Deen Dayal Upadhyay Gorakhpur University"    },
    { label: "Deccan College Postgraduate and Research Institute"    },
    { label: "Dayalbagh Educational Institute"    },
    { label: "Dibrugarh University"    },
    { label: "Dravidian University"    },
    { label: "University of Delhi"    },
    { label: "Dr. D.Y. Patil University"    },
    { label: "Eiilm University"    },
    { label: "Fatima mata national college kollam kerala"    },
    { label: "Forest Research Institute Dehradun"    },
    { label: "Govind Ballabh Pant University of Agriculture and Technology"    },
    { label: "Guru Ghasidas University"    },
    { label: "Gokhale Institute of Politics and Economics"    },
    { label: "Gandhi Institute of Technology and Managment"    },
    { label: "Guru Jambeshwar University"    },
    { label: "Gurukula Kangri University"    },
    { label: "Guru Nanak Dev University"    },
    { label: "Global Open University , Nagaland"    },
    { label: "Gujarat Technological University Ahmedabad"    },
    { label: "Gujarat University Ahmedabad"    },
    { label: "Gulbarga University"    },
    { label: "Gauhati University"    },
    { label: "Gurukul University"    },
    { label: "CCS Haryana Agricultural University"    },
    { label: "Chaudhary Charan Singh Haryana Agricultural University"    },
    { label: "Himachal Pradesh Agricultural University"    },
    { label: "Hemwati Nandan Bahuguna Garhwal University"    },
    { label: "Hidayatullah National Law University, Raipur"    },
    { label: "Sri Ramachardra Medical College and Research Institute"    },
    { label: "Himachal Pradesh University"    },
    { label: "Indian Agricultural Research Institute"    },
    { label: "IASE (Institute of Advanced Studies) Deemed University"    },
    { label: "ICFAI University"    },
    { label: "ICFAI University, Dehradun"    },
    { label: "ICFAI University, Tripura"    },
    { label: "ICFAI University, Sikkim"    },
    { label: "ICFAI University, Mizoram"    },
    { label: "ICFAI University, Meghalaya"    },
    { label: "ICFAI University, Jharkhand"    },
    { label: "ICFAI University, Nagaland"    },
    { label: "ICFAI University, Jaipur"    },
    { label: "ICFAI University, Raipur"    },
    { label: "ICFAI University, Himachal Pradesh"    },
    { label: "ICFAI University, Hyderabad"    },
    { label: "Indira Gandhi Agricultural University"    },
    { label: "Indira Gandhi Institute of Development and Research"    },
    { label: "Indira Gandhi Institute of Medical Sciences"    },
    { label: "Indira Gandhi National Open University"    },
    { label: "Indian Institute of Information Technology"    },
    { label: "Indian Institute of Information Technology and Management - Kerala"    },
    { label: "Indian Institute of Information Technology and Management - Gwalior"    },
    { label: "Indraprastha Institute of Information Technology, Delhi"    },
    { label: "International Institute of Information Technology, Pune"    },
    { label: "International Institute of Information Technology, Bhubaneswar"    },
    { label: "International Institute of Information Technology, Bangalore"    },
    { label: "Indian Institute of Management, Tiruchirappalli"    },
    { label: "Indian Institute of Information Technology, Guwahati"    },
    { label: "Indian Institute of Information Technology, Vadodara"    },
    { label: "Indian Institute of Information Technology, Kota"    },
    { label: "International Institute for Population Sciences"    },
    { label: "Indian Institute of Science"    },
    { label: "Indian Institute of Technology, Bombay"    },
    { label: "Indian Institute of Technology, Delhi"    },
    { label: "Indian Institute of Technology, Gandhinagar"    },
    { label: "Indian Institute of Technology, Guwahati" },
    { label: "Indian Institute of Technology, Hyderabad"    },
    { label: "Indian Institute of Technology, Kanpur"    },
    { label: "Indian Institute of Technology, Kharagpur"    },
    { label: "Indian Institute of Technology, Madras"    },
    { label: "Madras Institute of Technology"    },
    { label: "Indian Institute of Technology, Roorkee"    },
    { label: "Indian Institute of Technology, Patna"    },
    { label: "Indian Institute of Technology, Indore"    },
    { label: "Indian Institute of Technology, Jodhpur"    },
    { label: "University of Music and Fine Arts"    },
    { label: "Indian Law Institue"    },
    { label: "Indus University"    },
    { label: "Integral University"    },
    { label: "Guru Gobind Singh Indraprastha University"    },
    { label: "Indian School of Business Management and Administration"    },
    { label: "Indian Statistical Institute"    },
    { label: "Indian School of Mines (ISM)"    },
    { label: "Institute of Technology and Management"    },
    { label: "Indian University"    },
    { label: "Indian Veterinary Research Institute"    },
    { label: "Jadavpur University"    },
    { label: "First Global University to teaching Jainism"    },
    { label: "Jamia Hamdard University"    },
    { label: "University of Jammu"    },
    { label: "Jaypee Institute of Information Technology"    },
    { label: "Jiwaji University"    },
    { label: "Jamia Millia Islamia University"    },
    { label: "Jawaharlal Nehru Centre for Advanced  Scientific Research"    },
    { label: "Jawaharlal Nehru Agricultural University"    },
    { label: "Jawaharlal Nehru Technological University"    },
    { label: "Jawaharlal Nehru University"    },
    { label: "Jaipur National University"    },
    { label: "Jodhpur National University"    },
    { label: "Jai Prakash University"    },
    { label: "Rajasthan Vidyapeeth University"    },
    { label: "Jain Vishva Bharati Institute"    },
    { label: "Kalinga University"    },
    { label: "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya"    },
    { label: "Kannada University"    },
    { label: "Kannur University"    },
    { label: "Chhatrapati Shahu Ji Maharaj University"    },
    { label: "Kanpur University"    },
    { label: "Karnataka State Open University"    },
    { label: "Karpagam University"    },
    { label: "Karunya Institute Of Technology ( Deemed University)"    },
    { label: "University of Kashmir"    },
    { label: "Kerala Agricultural University"    },
    { label: "University of Kerala"    },
    { label: "Kohinoor School of Hospitality Management"    },
    { label: "University of Kalyani"    },
    { label: "Krishna University"    },
    { label: "Kameshwar Singh Darbhanga Sanskrit University"    },
    { label: "Karnataka State Law University"    },
    { label: "Karnatak University"    },
    { label: "Kerala University of Fisheries and Ocean Sciences"    },
    { label: "Kurukshetra University"    },
    { label: "Kumaraguru College of Technology"    },
    { label: "Kumaun University"    },
    { label: "Kuvempu University"    },
    { label: "Kakatiya University"    },
    { label: "L.D.College of Engineering"    },
    { label: "Lakshmibai National Institute of Physical Education"    },
    { label: "Lalit Narayan Mithila University"    },
    { label: "University of Lucknow"    },
    { label: "Mar Athanasios College for Advanced Studies"    },
    { label: "Magadh University"    },
    { label: "Mangalore University"    },
    { label: "Manipal University"    },
    { label: "Manipur University"    },
    { label: "Moulana Azad national Urdu University"    },
    { label: "Makanlal Chutur Vedi University"    },
    { label: "Makhanlal Chaturvedi National University of Journalism and Communication"    },
    { label: "Maharshi Dayanand Sarswati University Ajmer"    },
    { label: "Maharishi Dayanand University, Rohtak (Haryana )"    },
    { label: "Mahatma Gandhi Kashi Vidyapith"    },
    { label: "Maharaja Ganga Singh University, Bikaner"    },
    { label: "Mahatma Gandhi University, Kerala"    },
    { label: "Mahatma Jyotiba Phule Rohilkhand University Bareilly"    },
    { label: "Madurai Kamaraj University"    },
    { label: "Marathwada Agricultural University"    },
    { label: "Mohan Lal Sukhadia University"    },
    { label: "Motilal Nehru National Institute Of Technology"    },
    { label: "Madhya Pradesh Bhoj (Open) University"    },
    { label: "Mahatma Phule Agricultural University"    },
    { label: "Maharaja Sayajirao University of Baroda"    },
    { label: "University of Mumbai"    },
    { label: "Acharya Nagarjuna University"    },
    { label: "Nagaland University"    },
    { label: "Nagpur University"    },
    { label: "Nalanda Open University"    },
    { label: "National Museum Institute of History of Art, Conservation and Museology"    },
    { label: "University of North Bengal"    },
    { label: "National Dairy Research Institute"    },
    { label: "Narendra Deva University of Agriculture and Technology"    },
    { label: "North Eastern Hill University"    },
    { label: "Hemchandracharay North Gujarat University"    },
    { label: "National Institute of Mental Health and Neuro Sciences"    },
    { label: "Nizam's Institute of Medical Sciences"    },
    { label: "Institute of Management Studies"    },
    { label: "Nirma University"    },
    { label: "National Institute of Industrial Engineering"    },
    { label: "National Institute of Technology Agartala"    },
    { label: "National Institute of Technology Andhra Pradesh"    },
    { label: "National Institute of Technology Arunachal Pradesh"    },
    { label: "National Institute of Technology Calicut"    },
    { label: "National Institute of Technology Delhi"    },
    { label: "National Institute of Technology Durgapur"    },
    { label: "National Institute of Technology Goa"    },
    { label: "National Institute of Technology Hamirpur"    },
    { label: "National Institute of Technology Jamshedpur"    },
    { label: "National Institute of Technology Kurukshetra"    },
    { label: "National Institute of Technology Manipur"    },
    { label: "National Institute of Technology Meghalaya"    },
    { label: "National Institute of Technology Mizoram"    },
    { label: "National Institute of Technology Nagaland"    },
    { label: "National Institute of Technology Patna"    },
    { label: "National Institute of Technology Puducherry"    },
    { label: "National Institute of Technology Raipur"    },
    { label: "National Institute of Technology Rourkela"    },
    { label: "National Institute of Technology Sikkim"    },
    { label: "National Institute of Technology Silchar"    },
    { label: "National Institute of Technology Srinagar"    },
    { label: "National Institute of Technology Surathkal"    },
    { label: "National Institute of Technology Trichy"    },
    { label: "National Institute of Technology Uttarakhand"    },
    { label: "National Institute of Technology Warangal"    },
    { label: "National Law School of India University"    },
    { label: "Narsee Monjee Institute of Management Studies"    },
    { label: "North Maharashtra University"    },
    { label: "Netaji Subhas Institute of Technology"    },
    { label: "Osmania University"    },
    { label: "Sri Padmavati Women's University"    },
    { label: "Pandit Deendayal Petroleum University"    },
    { label: "Punjab Agricultural University"    },
    { label: "Dr. Panjabrao Deshmukh Krishi Vidyapeeth"    },
    { label: "Parul University"    },
    { label: "Punjab Engineering College"    },
    { label: "Pes University"    },
    { label: "Postgraduate lnstitute of Medical Education and Research"    },
    { label: "Pondicherry University"    },
    { label: "PSG College of Technology"    },
    { label: "Jai Narain Vyas University"    },
    { label: "Punjab Technical University"    },
    { label: "Panjab University"    },
    { label: "Punjabi University Patiala"    },
    { label: "Patna University"    },
    { label: "Rajendra Agricultural University"    },
    { label: "Rabindra Bharati University"    },
    { label: "Ranchi University"    },
    { label: "Rajasthan Agricultural University, Bikaner"    },
    { label: "Rani Durgavati University"    },
    { label: "Rajiv Gandhi Technical University (University of Technology of Madhya Pradesh)"    },
    { label: "Rajiv Gandhi University"    },
    { label: "Rajitlal Institute of Technology & Health Sciences (RITHS)"    },
    { label: "Dr. Ram Manohar Lohia Avadh University"    },
    { label: "Pandit Ravi Shankar Shukla University"    },
    { label: "Rajasthan Technical University"    },
    { label: "Mahatma Gandhi Chitrakut Gramoday University"    },
    { label: "Dr. Hari Singh Gour University, formerly University of Sagar"    },
    { label: "Sambalpur University"    },
    { label: "National Sanskrit University"    },
    { label: "SASTRA Deemed University"    },
    { label: "Sathyabama University"    },
    { label: "Saurashtra University"    },
    { label: "Shanmugha Arts Science Technology and Research Academy"    },
    { label: "Sree Chitra Tirunal Institute for Medical Sciences and Technology"    },
    { label: "Sardarkrushinagar Dantiwada Agricultural University"    },
    { label: "Sanjay Gandhi Postgraduate lnstitute of Medical Sciences"    },
    { label: "South Gujarat University"    },
    { label: "Shobhit University, Meerut"    },
    { label: "Shridhar University"    },
    { label: "Vikrama Simhapuri University"    },
    { label: "Symbiosis International University"    },
    { label: "Shri Jagannath Sanskrit University"    },
    { label: "Sido Kanhu Murmu University"    },
    { label: "Sher-E-Kashmir University of Agricultural Sciences and Technology"    },
    { label: "Sri Krishnadevaraya University"    },
    { label: "Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha"    },
    { label: "SMK Fomra Institute of Technology"    },
    { label: "Sikkim Manipal University of Health, Medical and Technological Sciences"    },
    { label: "Shreemati Nathibai Damodar Thackersey Women's University"    },
    { label: "Sikha 'O' Anushandhan University"    },
    { label: "South Asian University"    },
    { label: "School of Planning and Architecture"    },
    { label: "Periyar University"    },
    { label: "Sardar Patel University"    },
    { label: "Sri Sathya Sai Institute of Higher Learning"    },
    { label: "Sree Rama Krishna Degree College"    },
    { label: "SRM Institute Of Science & Technology ( Deemed University)"    },
    { label: "Swami Ramanand Teerth Marathwada University"    },
    { label: "Sri Sant Gajanan Maharaj College of Engineering"    },
    { label: "Sree Sankaracharya University of Sanskrit"    },
    { label: "Sampurnanand Sanskrit University"    },
    { label: "Solapur University"    },
    { label: "Sardar Vallabhai Patel University of Agriculture Amd Technology"    },
    { label: "Sardar Vallabhbhai National Institute of Technology"    },
    { label: "Sri Venkateswara Institute of Medical Sciences"    },
    { label: "Sri Venkateswara University"    },
    { label: "Tamil University"    },
    { label: "Tamil Nadu Veterinary and Animal Sciences University"    },
    { label: "Thiagarajar College of Engineering"    },
    { label: "Potti Sreeramulu Telugu University"    },
    { label: "Telugu University"    },
    { label: "Tezpur University"    },
    { label: "The New College"    },
    { label: "Thapar Institute of Engineering and Technology"    },
    { label: "Tata Institute of Social Sciences"    },
    { label: "Tilka Manjhi Bhagalpur University"    },
    { label: "Tilak Maharashtra Vidyapeeth"    },
    { label: "Tamil Nadu Dr. Ambedkar Law University"    },
    { label: "Tamil Nadu Dr. M.G.R. Medical University"    },
    { label: "Avinashilingam Institute for Home Science and Higher Education for Women"    },
    { label: "Gandhigram Rural Institute"    },
    { label: "Manonmaniam Sundaranar University"    },
    { label: "Mother Teresa Women's University"    },
    { label: "Maulana Azad National Institute of Technology Bhopal"    },
    { label: "Malaviya National Institute of Technology Jaipur"    },
    { label: "Tripura University"    },
    { label: "Takhatmal Shrivallabh Homoeopathic Medical College"    },
    { label: "Tumkur University"    },
    { label: "Thiruvalluvar University"    },
    { label: "University of Agricultural Sciences, Bangalore"    },
    { label: "University of Agricultural Sciences, Dharwad"    },
    { label: "Uttarakhand Technical University"    },
    { label: "University of Media Arts"    },
    { label: "University of Calicut"    },
    { label: "Goa University"    },
    { label: "University of Mysore"    },
    { label: "University of Pune"    },
    { label: "University of Rajasthan"    },
    { label: "Shivaji University"    },
    { label: "University of Madras"    },
    { label: "University of Hyderabad"    },
    { label: "University of Kota"    },
    { label: "University of Roorkee"    },
    { label: "Uttarakhand Open University"    },
    { label: "Uttar Pradesh Technical University"    },
    { label: "Utkal University"    },
    { label: "VBS Purvanchal University"    },
    { label: "Vinoba Bhave University"    },
    { label: "Vidyasagar University"    },
    { label: "Vignan University"    },
    { label: "Vikram University"    },
    { label: "Vinayaka Mission's Research Foundation-Deemed University"    },
    { label: "Visva-Bharati University"    },
    { label: "Vellore Institute of Technology"    },
    { label: "Veer Kunwar Singh University"    },
    { label: "Vardhaman Mahaveer Open University"    },
    { label: "Visvesvaraya National Institute of Technology"    },
    { label: "Veer Surendra Sai University of Technology"    },
    { label: "Visvesvaraya Technological University"    },
    { label: "West Bengal University of Animal and Fishery Sciences"    },
    { label: "West Bengal University of Technology"    },
    { label: "Yashawantrao Chavan Maharashtra Open University"    },
    { label: "Dr. YS Parmar University of Horticulture and Forestry"    },
    { label: "Charotar University of Science and Technology"    },
    { label: "Navrachana University"    },
    { label: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Gwalior"    }
]

for(let i=0;i<universities.length;i++)
{ 
    universities[i].id = i+1;
}

module.exports = universities;